Add Jacobi tutorial to documentation
fverdugo/PartitionedArrays.jl pull request #152
Opened 2024-06-06 06:41 UTC by GeliezaK

Added a tutorial on computing the 1D Jacobi method in parallel with PartitionedArrays to the documentation as a getting started page.

2024-06-06 07:20 UTC, fverdugo reviewed
Hi @GeliezaK 

the tutorial looks very good!

The documentation build is failing. Run it locally and try to reproduce the error? Maybe something related to mpi?

2024-06-06 07:33 UTC, GeliezaK commented
Hi @fverdugo, 
the issue did not appear when running it locally. So I have worked around it by putting the code that was executed with mpi in a markdown code block.

2024-06-06 08:59 UTC, fverdugo commented
Hi @GeliezaK 

Excellent Job!

Some minor comments:

- The output of @show and error messages (like when you index ranks[1]) do not show in the final page. Pleas rephrase the corresponding parts taking into account this. E.g, Perhaps remove the @show.

- Since we plan to add more tutorials (e.g. spmv), we need to create a new section called "Tutorials", and put this tutorial as the first one.

2024-06-10 13:23 UTC, GeliezaK commented
Hi @fverdugo , 
I wrapped the errorneous lines in try-catch-blocks, removed the `@show`, and added the tutorial to a new "Tutorials" section.

2024-06-13 09:48 UTC, fverdugo requested changes
See my minor comment.

2024-06-13 09:48 UTC, fverdugo commented on docs/src/jacobi_tutorial.md
Hi @GeliezaK 

just a final (minor comment).

Please remove this .md file from the repo as it is generated automatically.

2024-06-14 06:20 UTC, GeliezaK commented on docs/src/jacobi_tutorial.md
Thanks! I deleted it.

2024-06-14 09:12 UTC, fverdugo commented
@GeliezaK Thanks for this PR!

2024-06-14 09:13 UTC, merged